name: PR Assign

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  assign-author:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Assign PR author
        run: |
          # Get the PR author's username
          AUTHOR=$(jq -r .pull_request.user.login $GITHUB_EVENT_PATH)
      
          # Assign the PR to the author
          RESPONSE=$(curl -X POST -s -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          -d "{\"assignees\":[\"$AUTHOR\"]}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees")
      
          # Check if the assignment was successful
          if [ "$(echo "$RESPONSE" | jq -r '.message')" == "Not Found" ]; then
            echo "Assignment failed: PR not found."
            exit 1
          elif [ "$(echo "$RESPONSE" | jq -r '.html_url')" != "null" ]; then
            echo "Assignment succeeded."
          else
            echo "Assignment failed."
            exit 1
          fi

